
name: Regular testing
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Building
        uses: gradle/gradle-build-action@v2.8.1
        with:
          arguments: build
      - name: Testing
        uses: gradle/gradle-build-action@v2.8.1
        with:
          arguments: test
